/**
 * @fileoverview Public API surface of the `@tyrframework/cli` npm package — this is what
 * `package.json`'s `"exports"` field points `import ... from '@tyrframework/cli'` at. Deliberately
 * tiny: user command files (`~/.tyr/commands/*.tyr.ts`, generated by `sys/gen.ts`) live outside
 * this repository and can only import from the published package, not from internal relative
 * paths like `src/core/Kernel.ts` — so anything a command author needs (right now: just the
 * {@link TyrContext} type and the {@link TaskPriority} routing type/constant) has to be re-exported
 * here explicitly. Everything else in `src/core`/`src/lib` is an internal implementation detail
 * reached only through the `context` object a command factory receives, never imported directly.
 */
// Public API of @tyrframework/cli
// Import types from here in your ~/.tyr/commands/ files:
//   import type { TyrContext } from '@tyrframework/cli';

export type { TyrContext } from './core/Kernel.js';
export type { TaskPriority } from './lib/AIVendorManager.js';
export { TASK_PRIORITIES } from './lib/AIVendorManager.js';
